# core/utils/auto_coder.py
import os
import re
from core.utils.logging import log_info, log_error, log_success
from core.commands.handler_registry_utils import load_autogenerated_handlers
from config.settings import DEFAULT_LLM_PROVIDER
# Asumiendo que existe un cliente LLM (ej. Gemini/DeepSeek)
# Si no, esto es un esqueleto que el Arquitecto de Código rellenará

def generate_and_register_handler(request_text: str) -> bool:
    """
    Invoca al LLM (Arquitecto de Código) para generar un handler
    de Blender basado en la petición que el NLU no pudo entender.
    Ahora potenciado por Visión Multimodal de YouTube.
    """
    log_info(f"🚀 Iniciando Auto-Coding (Zuly AGI) para: '{request_text}'")
    
    # --- YOUTUBE KNOWLEDGE INGESTION ---
    from core.learning.youtube_learner import YouTubeVisionLearner
    learner = YouTubeVisionLearner()
    yt_data = learner.search_and_extract(request_text)
    
    youtube_context = ""
    if yt_data["success"]:
        youtube_context = f"""
        [CONTEXTO MULTIMODAL EXTRAÍDO DE YOUTUBE]
        Tutorial encontrado: {yt_data['title']}
        Enlace: {yt_data['video_url']}
        Transcripción (Lo que dice el humano):
        {yt_data['transcript'][:3000]} # Limitamos a 3000 chars por seguridad de tokens
        
        Imágenes extraídas: {len(yt_data['frames'])} fotogramas (Se pasan al modelo Vision internamente).
        Por favor usa este contexto para escribir la lógica exacta para Blender 3.6.
        """
    else:
        youtube_context = "No se encontró contexto en YouTube. Usa tu conocimiento interno sobre Blender 3.6."
    # -----------------------------------
    
    # 1. Limpiar el nombre del handler basado en la petición
    safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', request_text.lower()[:30]).strip('_')
    handler_name = f"blender.auto_{safe_name}"
    func_name = f"auto_{safe_name}_handler"
    
    # 2. Generar código (Aquí iría la llamada real a DeepSeek/Gemini)
    # Por ahora simulamos la generación con un bloque try-except seguro
    generated_code = f'''
from core.commands.handler_registry_utils import blender_handler
from core.utils.logging import log_info

@blender_handler("{handler_name}")
def {func_name}(context=None, **kwargs):
    """
    Handler autogenerado para: {request_text}
    Contexto usado: {youtube_context}
    """
    log_info("Ejecutando handler autogenerado con visión de YouTube: {handler_name}")
    try:
        import bpy
        # Espacio para el código generado por IA multimodal...
        # bpy.ops...
        return {{"success": True, "message": "Autogenerado ejecutado con éxito"}}
    except Exception as e:
        return {{"success": False, "error": str(e)}}
'''
    
    # 3. Guardar el archivo en la carpeta de autogenerated
    target_dir = os.path.join(os.getcwd(), "core", "commands", "blender_handlers", "autogenerated")
    os.makedirs(target_dir, exist_ok=True)
    
    file_path = os.path.join(target_dir, f"auto_{safe_name}.py")
    
    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(generated_code)
            
        log_success(f"✓ Handler escrito en disco: {file_path}")
        
        # 4. Recargar módulos en caliente (Hot-Reload)
        load_autogenerated_handlers()
        log_success(f"✓ Sistema auto-expandido con {handler_name}. ¡Listo para usar!")
        return True
        
    except Exception as e:
        log_error(f"Fallo en Auto-Coding: {e}")
        return False
