# core/commands/handler_registry_utils.py

import os
import importlib
import pkgutil
from typing import Callable, Dict

# Diccionario global para recolectar handlers dinámicos
_dynamic_handlers = {}

def blender_handler(command_name: str) -> Callable:
    """
    Decorador para registrar automáticamente un handler de Blender.
    Ejemplo:
        @blender_handler("blender.create_custom_mesh")
        def my_custom_handler(context, **kwargs):
            ...
    """
    def decorator(func: Callable) -> Callable:
        _dynamic_handlers[command_name] = func
        return func
    return decorator

def get_dynamic_handlers() -> Dict[str, Callable]:
    """Retorna los handlers registrados dinámicamente."""
    return _dynamic_handlers

def load_autogenerated_handlers():
    """
    Escanea la carpeta de handlers autogenerados e importa los módulos
    para que se ejecuten los decoradores.
    """
    import core.commands.blender_handlers.autogenerated as autogen
    
    # Obtener la ruta del paquete autogenerated
    if not hasattr(autogen, '__path__'):
        return
        
    for _, module_name, _ in pkgutil.iter_modules(autogen.__path__):
        full_module_name = f"core.commands.blender_handlers.autogenerated.{module_name}"
        try:
            # Importar el módulo fuerza la ejecución de los decoradores
            importlib.import_module(full_module_name)
        except Exception as e:
            print(f"[ZULY] Error cargando handler autogenerado {full_module_name}: {e}")
